apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: node-app
  name: node-app
  namespace: node-app
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'node-openshift:0.1'
  runPolicy: Serial
  source:
    contextDir: app
    git:
      uri: https://github.ibm.com/garghitesh/nodejs_openshift_minishift.git
    sourceSecret:
      name: github-secret
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:10
        namespace: openshift
    type: Source
  triggers:
  - imageChange:
    type: ImageChange
  - type: ConfigChange  
  - github:
      secret: github-secret
    type: GitHub